### ISSUE TITLE
Bug in Settings handling

### ISSUE THREAD

**Issue by LukeTowers** [firemankurt/MyCalendar#23]
If you go to the settings page for the plugin and save the settings; then reload the page, the Day Start Time, Day End Time, and Default Event Length values are all 00:00 - regardless of what value was originally specified.

**Comment by LukeTowers** [comment]
As mentioned here: https://octobercms.com/plugin/support/kurtjensen-mycalendar/reload-or-refresh-of-mycalendar-produces-incorrect-dates-in-mycalendarsettings?page=1#post-18120

**Comment by LukeTowers** [comment]
As a side note, the PR is really a temporary solution. A couple things about the Setting model in general stand to be improved. 

Currently you have accessors for some of the values, you shouldn't even need them because you should be able to store the correct data that you actually need and not have to modify it to make it valid. Couple of options there, use a mutator to modify the data before saving it, or just configure the timepicker widgets to store the correct value from the get go (http://octobercms.com/docs/backend/forms#widget-datepicker, specify `format: H:i`)

Secondly, try to avoid rolling your own DateTime manipulation methods through use of string manipulation functions - doing so will only lead to endless headaches like this believe me. Instead, look at using something well established like Carbon (which is included in Laravel and OctoberCMS by default).

**Comment by firemankurt** [comment]
First of all thank you for reporting issue.

Second, this was caused by some of the many changes to the datepicker here https://github.com/octobercms/october/commit/e772e87de5c678fd12e1eb68bfbced97fb90072f  I had just not caught the issue because I had not retested the settings since I had not modified my code there.

Third - Setting `format: H:i` does nothing for how the value is saved.  Here is the post data with day_start field set to `format: H:i `:

Settings[public_perm]:10
Settings[deny_perm]:11
Settings[default_perm]:11
Settings[date_format]:F jS, Y
Settings[time_format]:g:i a
Settings[day_start]:2017-01-23 01:40:00
Settings[day_end]:2017-01-23 02:50:00
Settings[default_length]:2017-01-23 12:00:00
Settings[boostrap_cdn]:

As you can see it submits a full datetime value.

Forth - I normally avoid "rolling your own" date methods. But the amount of code needed to turn the former values from "HH:MM:SS" to "HH:MM" using something like Carbon did not appear efficient.  And  `substr($time, 0, 5)` worked quite handily.

I will be working on a fix tonight.
