### ISSUE TITLE
Displays duplicate events

### ISSUE THREAD

**Issue by ribsousa** [firemankurt/MyCalendar#4]
After upgrading to version 1.0.17, the event list component is displaying the list of events with duplicate events.

![Duplicate Events](http://iepmdf.com.br/storage/app/media/dplicate-events.jpg)

**Comment by firemankurt** [comment]
ribsousa, Thanks for posting.  I am having trouble reproducing this issue on my installation.  Could you please show me your page.html file from the "october/themes/themename/pages/" directory so I can better solve this?

Thanks...

**Comment by ribsousa** [comment]
Here's!
![page home](http://iepmdf.com.br/storage/app/media/Clipboard01.jpg)

**Comment by firemankurt** [comment]
I see the issue:

    {% set m = date()|date('m')+1 %} // is equal to 13 so it is not a valid month

I will change EventList tonight to make it show all future dates and account for change from Dec to Jan.  I am also going to add an "End date" to Events so you can decide how far into future to grab events.

Those two changes will allow you to accomplish your goals without fancy code in your page.

**Comment by firemankurt** [comment]
Should be fixed in 1.0.18.
- Changed DB fields from year,month and day to a more standard date field.
- Simplified queries by adding scopes to event model.
- Removed unused properties from EVList Component.
- Added ability to set days in Future and days in Past to be included in query for Event Component.

Please review instructions for creating an Event List.

Thanks for your patients.
